
minimal_mistakes_skin: "contrast"
search: true

title: "PizzaRobotics"
subtitle: ":pizza: We are ItalianMakers. We make Robots. In Pizza we crust"
name: "PizzaRobotics"

repository: "pizzarobotics/pizzarobotics.github.io"

twitter_username: pizzarobotics
github_username: pizzarobotics

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

after_footer_scripts :
  - /assets/js/cookie-consent.js
  - /assets/js/copyCode.js

# Site Footer
footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://pizzarobotics.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pizzarobotics"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/pizzarobotics"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCVh659_qQa_bjDOg3Jhyf_w"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/pizzarobotics"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:info@pizzarobotics.org"

teaser: assets/images/pizzarobotics.png

collections:
  team:
    output: true
    permalink: /:collection/:path/
  event:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  # _event
  - scope:
      path: ""
      type: event
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
  # _team
  - scope:
      path: ""
      type: team
    values:
      layout: single
      author_profile: false
      share: true
      read_time: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - README.md
  - LICENSE

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
